services:
  - type: web
    name: kmi-lupic-lab
    env: python
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build && pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: SESSION_COOKIE_SECURE
        value: 'true'
      - key: PYTHON_VERSION
        value: 3.11.0
